package models

import (
	"time"
)

//go:generate easyjson -all models.go

//easyjson:json
type FullURL struct {
	URL string `json:"url"`
}

//easyjson:json
type ShortURL struct {
	Result string `json:"result"`
}

//easyjson:json
type DBShortenRowList []DBShortenRow

//easyjson:json
type DBShortenRow struct {
	ID        int       `json:"id"`
	Hash      string    `json:"hash"`
	URL       string    `json:"url"`
	Time      time.Time `json:"time"`
	UserID    string    `json:"user_id"`
	IsDeleted bool      `json:"is_deleted"`
}

//easyjson:json
type BatchShortenRequestList []BatchShortenRequest

//easyjson:json
type BatchShortenRequest struct {
	ID  string `json:"correlation_id"`
	URL string `json:"original_url"`
}

//easyjson:json
type BatchShortenResponseList []BatchShortenResponse

// BatchShortenResponse represents the response for a single item
// in a batch shorten request. It contains the client-provided correlation ID
// and the generated shortened URL.
type BatchShortenResponse struct {
	// ID is the correlation identifier provided by the client
	// to match requests and responses.
	ID string `json:"correlation_id"`

	// Hash is the shortened URL generated by the service.
	Hash string `json:"short_url"`
}

//easyjson:json
type UserLinksResponseList []UserLinksResponse

// UserLinksResponse represents a single shortened link belonging to a user.
// It contains both the original URL and its shortened form.
type UserLinksResponse struct {
	// Short is the shortened URL returned by the service.
	Short string `json:"short_url"`

	// Original is the original, unmodified URL provided by the user.
	Original string `json:"original_url"`
}

//easyjson:json
type IDList struct {
	IDs []string `json:"ids"`
}
